server:
    port: 80  # Server port

spring:
    datasource:
        url: jdbc:mysql://YOUR_DATABASE_HOST:3306/YOUR_DATABASE_NAME  # Database connection URL
        username: YOUR_DATABASE_USERNAME  # Database username
        password: YOUR_DATABASE_PASSWORD  # Database password
        driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver

    jpa:
        hibernate:
            ddl-auto: create  # create: create tables, create-drop: create on startup/drop on shutdown, update: update schema
        show-sql: true  # Show SQL queries in logs
        properties:
            hibernate:
                 dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.0 dialect