server:
    port: 80  # 서버 포트 (개발용: 8080, 운영용: 80)

spring:
    datasource:
        url: jdbc:mysql://YOUR_DATABASE_HOST:3306/YOUR_DATABASE_NAME  # 데이터베이스 연결 URL
        username: YOUR_DATABASE_USERNAME  # 데이터베이스 사용자명
        password: YOUR_DATABASE_PASSWORD  # 데이터베이스 비밀번호
        driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버

    jpa:
        hibernate:
            ddl-auto: create  # create: 테이블 생성, create-drop: 시작시 생성/종료시 삭제, update: 스키마 업데이트
        show-sql: true  # SQL 쿼리 로그 출력 여부
        properties:
            hibernate:
                 dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.0 방언